name: getx_flutter_blank_project
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  flutter_inappwebview: ^5.7.2+3
  responsive_framework: ^0.2.0
  dio: ^4.0.6
  url_launcher: ^5.2.7
  logger: ^1.1.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    #音频文件
    - assets/audios/
    #图片文件
    - assets/images/
    - assets/images/root/
    - assets/images/splash/
  # fonts:
    # - family: ShadowsIntoLight-Regular
    #   fonts:
    #     - asset: assets/ShadowsIntoLight-Regular.ttf
